apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qr2x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qr2x
    app.kubernetes.io/part-of: ci10t-776-0053-app
  name: devfile-sample-qr2x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qr2x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qr2x
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0053-tenant/ci10t-776-0053-app/devfile-sample-qr2x@sha256:df14d00bc650fee2ac0c87bc1b9025abd936a7ef262a7bcdbbf797146b01f40c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
