apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qr2x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0053-tenant/ci10t-776-0053-app/devfile-sample-qr2x@sha256:df14d00bc650fee2ac0c87bc1b9025abd936a7ef262a7bcdbbf797146b01f40c
        name: my-nodejs
        resources: {}
status: {}
